server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.184.129
    virtual-host: leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4GCzQz9wXm94KBzXvvjY # 你自己的accessKeyId
    accessKeySecret: tjUp4fftRYCPX37eUWFjiHmu9Cj06N # 你自己的AccessKeySecret
    signName: 试用阿里云短信服务 # 签名名称
    verifyCodeTemplate: SMS_205133491 # 模板名称
